Wrap sigma parameter with as_tensor_variable() before get_tau_sigma()
For the cases where the sigma parameter is a vector of random variables instead of fixed values, 
in get_tau_sigma if np.any(sigma_ <= 0) throws the following error:
TypeError: Variables do not support boolean operations. Sigma parameter normally is wrapped by as_tensor_variable() after get_tau_sigma. Moving the line sigma= pt.as_tensor_variable(sigma)
before get_tau_sigma() resolves this issue.