mc_error: Update for trimmed shape
Pass numpy.resize the trimmed shape instead of the old shape.  This
avoids the error below.

    Traceback (most recent call last):
    [...]
      File "[...]/pymc3/stats.py", line 195, in mc_error
        batched_traces = np.resize(x[:-resid], (batches, len(x)/batches))
      File "[...]/numpy/core/fromnumeric.py", line 1128, in resize
        return reshape(a, new_shape)
      File "[...]/numpy/core/fromnumeric.py", line 225, in reshape
        return reshape(newshape, order=order)
    ValueError: total size of new array must be unchanged

This was showing up as an error in the "short" Travis run of
examples/best.py under python 3 (but not python 2, for some reason).